export const CONSTANTS = {
  CLASS_NAMES: {
    LIST_ENTRY_CONTROL: "list-entry-control",
    LIST_ENTRY_DATE_FROM: "list-entry-date-from",
    LIST_ENTRY_DATE_TO: "list-entry-date-to",
    LIST_ENTRY: "list-entry",
    LIST_ENTRY_PERCENT: "list-entry-percent",
    LIST_ENTRY_REASON: "list-entry-reason",
    CLICKABLE: "clickable",
    CONTROL_SELECTED: "control-selected",
    ICON_DISABLED: "icon-disabled",
    PAGE_MAIN: "page-main",
    SELECTABLE: "selectable",
    SORTABLE: "sortable",
    SORTED: "sorted",
    SORTED_ASC: "sorted-asc",
    SORTED_DESC: "sorted-desc",
    SORT_ICON: "sort-icon",
  },
  IDS: {
    ABSENCE_DATE_FROM: "absence-from",
    ABSENCE_DATE_TO: "absence-to",
    ABSENCE_PERCENT: "absence-percent",
    ABSENCE_REASON: "absence-reason",
    ABSENCE_ENTRY_LIST: "absence-entries",
    ABSENCE_HEADER: "absence-header",
    BTN_ADD_ABSENCE: "btn-add-absence-entry",
    BTN_DELETE_ABSENCE: "btn-delete-absence-entry",
    EMPLOYMENT_HEADER: "employment-header",
    EMPLOYMENT_LIST: "employment-list",
  },
  ABSENCE_REASONS: [
    "Sickness",
    "Accident",
    "Military/Other",
    "Pregnancy",
    "Maternity",
  ],
  CONTROL_TYPES: {
    LIST_ENTRY_DATE_FROM: "list-entry-date-from",
    LIST_ENTRY_DATE_TO: "list-entry-date-to",
    LIST_ENTRY_PERCENT: "list-entry-percent",
  },
  SORT_STATUS: {
    ASC: "asc",
    DESC: "desc",
    NONE: "none",
  },
  SORT_FIELDS: {
    FROM: "FROM",
    TO: "TO",
    PERCENT: "PERCENT",
    REASON: "REASON",
  },
  ENTRY_TYPES: {
    ABSENCE: "ABSENCE",
    EMPLOYMENT: "EMPLOYMENT",
  },
};
